### ISSUE TITLE
<script setup lang="ts"> 时vscode提示错误

### ISSUE THREAD

**Issue by dmskys** [sonofmagic/uni-app-vue3-for-amap-wx#1]
无法找到模块“@/lib/amap-wx.130.js”的声明文件

**Comment by sonofmagic** [comment]
哦哦，我默认用的 typescript ,这个下载到的就是 js 文件，没有 .d.ts 文件，你直接忽略这个模块，或者 declare module 一下就行

**Comment by dmskys** [comment]
声明上了这个declare module 'AMapWX'; 不起作用.

**Comment by sonofmagic** [comment]
那我们干脆这样写
```js
// @ts-ignore
import amapFile from '../../lib/amap-wx.130.js'
```
高德地图这个 sdk 的确官方没有给 .dts 文件，自己维护也挺烦的

**Comment by dmskys** [comment]
又发现一个问题 npm run dev:mp-weixin 时 无法加载模块
vite v2.9.6 building for development...
Error when using sourcemap for reporting an error: Can't resolve original location of error.
'default' is not exported by src/lib/amap-wx.130.js, imported by src/pages/order/create.vue
at pages/order/create.vue:14:7
  12: import { reactive, toRefs } from "vue";
  13: import { useUserStore } from "@/store/modules/user";
  14: import amapFile from "@/lib/amap-wx.130.js";

**Comment by sonofmagic** [comment]
你是用的我这个 `demo` 吗？我这里面额外安装了 `@rollup/plugin-commonjs` ，注册在 `vite.config.ts` 来加载 `amap-wx.130.js`，你可以看一下我项目里的 `README.md` 文件的呢。

**Comment by dmskys** [comment]
不好意思，忘记配置vite.config.ts了  可以了 谢谢！

**Comment by dmskys** [comment]
不好意思，编译没问题，运行又出问题了。。。
17:40:02 [vite] [plugin:vite:import-analysis] Failed to resolve import "commonjsHelpers.js" from "src/lib/amap-wx.130.js". Does the file exist?
at lib/amap-wx.130.js:1:35
  1  |  import * as commonjsHelpers from "commonjsHelpers.js";

运行你的demo 加上<script setup lang="ts"> 也是这个结果，你下班可以看看，顺便写个ts的demo吧。

**Comment by sonofmagic** [comment]
我最新的demo里面，把原先的2个文件，都改成了 `lang="ts"` 的形式，并没有复现这个错误，都是可以正常运行的。
你是不是没有加环境变量？可以像我 `.env.sample` 那样配置一下 `.env`  里的值，地图信息就有了。
![image](https://user-images.githubusercontent.com/15621541/169050022-65b90b34-27f9-4850-97b3-911b7c1241a2.png)

**Comment by dmskys** [comment]
明天我试试，谢谢

**Comment by dmskys** [comment]
我这里还是没有解决，用的你的demo。
[
![网页捕获_19-5-2022_8515_192 168 1 7](https://user-images.githubusercontent.com/5857415/169179237-88c719df-f0d5-4b44-bc4b-ebe5cb9ac5ed.jpeg)
](url)

**Comment by dmskys** [comment]
本地版本信息：

➜  uni-app-vue3-for-amap-wx git:(main) ✗ npm --version
8.10.0
➜  uni-app-vue3-for-amap-wx git:(main) ✗ npm info vue version
3.2.33
➜  uni-app-vue3-for-amap-wx git:(main) ✗ npm info vite version 
2.9.9
➜  uni-app-vue3-for-amap-wx git:(main) ✗

**Comment by sonofmagic** [comment]
我怀疑是nodejs 版本的问题，我的 nodejs版本是 16
`@rollup/plugin-commonjs` `22` 这个版本最低要求的nodejs版本是 `12`
https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#v2200
可以给这个包降级试试

**Comment by dmskys** [comment]
➜  uni-app-vue3-for-amap-wx git:(main) ✗ node -v
v17.7.2
我的nodejs 版本是17 你升级到17看看

**Comment by sonofmagic** [comment]
额,nodejs我自己是不用奇数版本的.....你这个问题我去看看issue把

**Comment by dmskys** [comment]
我改回node 16试试

**Comment by sonofmagic** [comment]
https://github.com/rollup/plugins/issues/986
你给 @rollup/plugin-commonjs 降级到 21 试试， 22这个版本有些机器有问题。

**Comment by dmskys** [comment]
试了下，跟nodejs版本没有关系，node 16版本问题依旧存在，确实是插件的版本的问题， "@rollup/plugin-commonjs": "21.1.0" 问题解决。
